name: Deploy docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/ci_docs.yml'
      - 'projects/docs/**'

env:
  HUSKY: 0

concurrency:
  group: deploy-docs-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: dsi-hug/actions/setup@v2

      - name: Build docs
        working-directory: projects/docs
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DSI_HUG_BOT_GITHUB_TOKEN }}
          publish_dir: ./projects/docs/build
          user_name: dsi-hug-bot
          user_email: 'dsi-hug-bot@users.noreply.github.com'
