name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - 'projects/docs/**'

concurrency:
  group: run-tests-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_tests:
    uses: dsi-hug/actions/.github/workflows/action.yml@v3
    with:
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-versions: '[20, 22]'
      working-directory: projects/lib
      lint: true
      test: true
      build: true
